services:
  # ğŸ¦ 1. TITAN CORE BANKING APP
  titan-app:
    build: .             # Build á–á¸ Dockerfile áŠáŸ‚á›á™á¾á„á”á„áŸ’á€á¾áá˜á»á“á“áŸáŸ‡
    container_name: titan-core-app
    ports:
      - "8080:8080"      # Host Port : Container Port
    environment:
      # âš ï¸ áŸáŸ†áá¶á“áŸ‹: á áŸ…á‘áŸ… Database áá¶á˜áˆáŸ’á˜áŸ„áŸ‡ Service "postgres-db"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/titandb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      # âš ï¸ áŸáŸ†áá¶á“áŸ‹: á áŸ…á‘áŸ… Redis áá¶á˜áˆáŸ’á˜áŸ„áŸ‡ Service "redis-cache"
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - postgres-db
      - redis-cache
    networks:
      - titan-network
    restart: always

  # ğŸ—„ï¸ 2. POSTGRES DATABASE
  postgres-db:
    image: postgres:15-alpine
    container_name: titan-db-prod
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=titandb
    ports:
      - "5432:5432"
    volumes:
      - titan_db_data:/var/lib/postgresql/data # Persistent Data (á€á»áŸ†á±áŸ’á™á”á¶ááŸ‹á‘á·á“áŸ’á“á“áŸá™á–áŸá›á”á·á‘)
    networks:
      - titan-network
    restart: always

  # âš¡ 3. REDIS CACHE
  redis-cache:
    image: redis:alpine
    container_name: titan-redis-prod
    ports:
      - "6379:6379"
    networks:
      - titan-network
    restart: always

# ğŸŒ NETWORK DEFINITION
networks:
  titan-network:
    driver: bridge

# ğŸ’¾ VOLUME DEFINITION
volumes:
  titan_db_data: